# Generated by Django 2.0.6 on 2019-01-14 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(max_length=254, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Caixa',
                'verbose_name_plural': 'Caixas',
            },
        ),
        migrations.CreateModel(
            name='CaixaSelect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('caixa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Caixa', verbose_name='Caixas')),
            ],
            options={
                'verbose_name': 'Caixa Cadastrado',
                'verbose_name_plural': 'Caixas Cadastrados',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('tipo_usuario', models.CharField(choices=[('Gerente', 'Gerente'), ('Operador', 'Operador'), ('Supervisor', 'Supervisor'), ('Master', 'Master')], max_length=30, verbose_name='Tipo Usuário')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('sms_code', models.CharField(blank=True, max_length=4, null=True)),
                ('sms_date', models.DateTimeField(blank=True, null=True)),
                ('sms_resends', models.IntegerField(blank=True, default=0, null=True)),
                ('confirmation_sms', models.BooleanField(default=False)),
                ('caixa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='client.CaixaSelect', verbose_name='Caixas')),
                ('gerente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_gerente', to='client.Usuario')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_supervisor', to='client.Usuario')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.AddField(
            model_name='caixa',
            name='usuario_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_responsavel', to='client.Usuario', verbose_name='Usuário Responsável'),
        ),
    ]
