# Generated by Django 2.0.6 on 2019-02-10 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaoReal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id_zoop', models.CharField(blank=True, max_length=200, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('cvc', models.IntegerField(blank=True, null=True)),
                ('nome_cartao', models.CharField(blank=True, max_length=200, null=True)),
                ('validade', models.CharField(blank=True, max_length=200, null=True)),
                ('bandeira', models.CharField(blank=True, max_length=200, null=True)),
                ('is_prioritario', models.BooleanField(default=False)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('quantidade_uso', models.IntegerField(blank=True, null=True)),
                ('tipo_cartao', models.CharField(blank=True, choices=[('Débito', 'Débito'), ('Crédito', 'Crédito')], max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Cartão Real',
            },
        ),
        migrations.CreateModel(
            name='CartaoVigente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('cvc', models.IntegerField(blank=True, null=True)),
                ('nome_cartao', models.CharField(blank=True, max_length=200, null=True)),
                ('validade', models.CharField(blank=True, max_length=200, null=True)),
                ('bandeira', models.CharField(blank=True, max_length=200, null=True)),
                ('is_vigente', models.BooleanField(default=False)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('quantidade_uso', models.IntegerField(blank=True, null=True)),
                ('modo_cartao', models.CharField(blank=True, choices=[('Físico', 'Físico'), ('Virtual', 'Virtual')], max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Cartão Vigente',
            },
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('data_transacao', models.DateField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=12, max_digits=14, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=12, max_digits=14, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('local', models.CharField(blank=True, max_length=200, null=True)),
                ('cnpj_logista', models.CharField(blank=True, max_length=200, null=True)),
                ('is_parcelado', models.BooleanField(default=False)),
                ('quantidade_parcelas', models.IntegerField(blank=True, null=True)),
                ('cartao_real', models.ManyToManyField(blank=True, to='client.CartaoReal')),
                ('cartao_vigencia', models.ManyToManyField(blank=True, to='client.CartaoVigente')),
            ],
            options={
                'verbose_name': 'Transação',
            },
        ),
        migrations.RemoveField(
            model_name='caixa',
            name='usuario_responsavel',
        ),
        migrations.RemoveField(
            model_name='caixaselect',
            name='caixa',
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuário'},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='caixa',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='gerente',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_usuario',
        ),
        migrations.DeleteModel(
            name='Caixa',
        ),
        migrations.DeleteModel(
            name='CaixaSelect',
        ),
        migrations.AddField(
            model_name='transacao',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='client.Usuario'),
        ),
    ]
