# Generated by Django 2.0.6 on 2019-02-10 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20190210_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cartao_real',
            field=models.ManyToManyField(blank=True, to='client.CartaoReal'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cartao_vigencia',
            field=models.ManyToManyField(blank=True, to='client.CartaoVigente'),
        ),
        migrations.RemoveField(
            model_name='transacao',
            name='cartao_real',
        ),
        migrations.AddField(
            model_name='transacao',
            name='cartao_real',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='client.CartaoReal'),
        ),
        migrations.RemoveField(
            model_name='transacao',
            name='cartao_vigencia',
        ),
        migrations.AddField(
            model_name='transacao',
            name='cartao_vigencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='client.CartaoVigente'),
        ),
    ]
