# Generated by Django 2.0.6 on 2019-02-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20190210_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='id_zoop',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
